### ISSUE TITLE
sourceLinks and targetLinks appear to be flipped

### ISSUE THREAD

**Issue by emeeks** [tomshanley/d3-sankey-circular#14]
It looks like the targetLinks and sourceLinks should be reversed for nodes.

**Comment by tomshanley** [comment]
whereabouts in the code is this, or is it throughout

**Comment by tomshanley** [comment]
Inspecting a node, like this one https://bl.ocks.org/tomshanley/raw/d01b00c17a5ebe76779c26f82ab9d7ec/, it has properties:

- sourceLinks: lists the links which have this node as the source (start of the link)
- targetLinks:  lists the links which have this is the target (end of the link)

This seems right to me.  Am I looking the right place, or got something wrong here?

**Comment by emeeks** [comment]
You might be right, Tom, I will go back and take a look and let you know. Sorry for the false alarm if so.
