### ISSUE TITLE
bundle with rollupjs

### ISSUE THREAD

**Issue by micahstubbs** [tomshanley/d3-sankey-circular#18]
a dependency for #17

**Comment by micahstubbs** [comment]
will take a stab at this

**Comment by micahstubbs** [comment]
modeling this on https://github.com/rollup/rollup-starter-lib/tree/babel

**Comment by micahstubbs** [comment]
also taking inspiration from this config https://github.com/nbremer/d3-loom/blob/master/rollup.config.js

**Comment by tomshanley** [comment]
@micahstubbs Is this issue now resolved, or do you plan more updates?

**Comment by micahstubbs** [comment]
this one is complete 😄 
https://github.com/tomshanley/d3-sankey-circular/pull/19
