### ISSUE TITLE
Can't import the named export ... from non EcmaScript module

### ISSUE THREAD

**Issue by peteruithoven** [tomshanley/d3-sankey-circular#32]
I can't seem to import this module in a webpack based project. I'm getting these errors:
```
ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 451:16-25
Can't import the named export 'ascending' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 981:23-37
Can't import the named export 'linkHorizontal' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 309:19-22
Can't import the named export 'map' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 1485:16-19
Can't import the named export 'max' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 352:20-23
Can't import the named export 'max' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 386:20-23
Can't import the named export 'max' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 557:31-35
Can't import the named export 'mean' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 556:31-35
Can't import the named export 'mean' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 28:74-77
Can't import the named export 'min' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 863:13-16
Can't import the named export 'min' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 1482:16-19
Can't import the named export 'min' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 475:15-18
Can't import the named export 'min' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 449:18-22
Can't import the named export 'nest' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 476:53-56
Can't import the named export 'sum' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 330:58-61
Can't import the named export 'sum' from non EcmaScript module (only default export is available)
 @ ./src/index.js

ERROR in ./node_modules/d3-sankey-circular/dist/d3-sankey-circular.mjs 330:28-31
Can't import the named export 'sum' from non EcmaScript module (only default export is available)
 @ ./src/index.js
```

Simple example: https://github.com/peteruithoven/d3-sankey-circular-test

**Comment by peteruithoven** [comment]
@micahstubbs I see you've contributed to the bundling logic, could you help with this?

**Comment by micahstubbs** [comment]
hello hello, will have a look 👋

**Comment by micahstubbs** [comment]
hi @peteruithoven here's a pull request that fixes your example.  short story:  it looks like we cannot consume javascript modules (`.mjs`) files in webpack 4 without telling webpack how to parse those files.  the solution that I suggest adds a `webpack.config.js` file that tells webpack how to parse the `.mjs` file that `d3-circular-sankey` ships.

PR https://github.com/peteruithoven/d3-sankey-circular-test/pull/1

**Comment by micahstubbs** [comment]
@tomshanley this is a client code issue (not a `d3-circular-sankey` source code issue). in order to use `.mjs` files in webpack, webpack users need to know how to configure webpack. you can probably close this issue.

**Comment by tomshanley** [comment]
thanks for providing that help Micah - appreciate that it helps people use this library

**Comment by micahstubbs** [comment]
for people who come here later from search with the same problem, you need to make sure that you have a `webpack.config.js` file in the root of your project directory that looks something like this:

```javascript
const config = {
  mode: 'production', // "production" | "development" | "none"
  resolve: {
    extensions: ['*', '.mjs', '.js', '.json']
  },
  module: {
    rules: [
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      }
    ]
  }
}

module.exports = config
```

**Comment by peteruithoven** [comment]
@micahstubbs thanks for looking into this, and creating a PR for my example. 

I do think that the solution shouldn't be having all users customize their Webpack config though, especially since webpack's is trying to be zero config. I think this is even more important for people using tools like create-react-app, vue-cli who might not even realize that they are using webpack.

> Since version 4.0.0, webpack does not require a configuration file to bundle your project, nevertheless it is incredibly configurable to better fit your needs.

From: https://webpack.js.org/concepts

To quote another issue:
> Files ending with `.mjs` are parsed as `javascript/esm`, a stricter mode. This mode does not allow to import CJS modules like ESM ones.
> 
> While this issue looks like a webpack one, it is not: `react-apollo` should correctly import non-ESM dependencies, in this case `react`.

From: https://github.com/apollographql/react-apollo/issues/1737

> Nice! Just remember Webpack's defaults are the way they are for a reason. `.mjs` is limited because it's not fully baked and it's support story isn't finished yet. If you need `javascript/auto` you should really be using `.js`.

From: https://github.com/apollographql/react-apollo/issues/1737#issuecomment-373039056

**Comment by peteruithoven** [comment]
The `.mjs` version performs these imports:
```
import { min, ascending, max, mean, sum } from 'd3-array';
import { map, nest } from 'd3-collection';
import { linkHorizontal } from 'd3-shape';
import findCircuits from 'elementary-circuits-directed-graph';
```
I'm assuming from those the one listed in the errors are not valid `esm` (EcmaScript module). 

If I go into `node_modules` and change the filename from `.mjs` to `.esnext.js` (there is probably a better name convention out there) and update in `package.json` the `module` field it also works, but it doesn't require customizing the webpack config.

**Comment by peteruithoven** [comment]
Another solution seems to be to use default exports:
``` js
import d3Array from 'd3-array';
import d3Collection from 'd3-collection';
import d3Shape from 'd3-shape';
import findCircuits from 'elementary-circuits-directed-graph';

const { min, ascending, max, mean, sum } = d3Array;
const { map, nest } = d3Collection;
const { linkHorizontal } = d3Shape;
```

**Comment by peteruithoven** [comment]
Or, possibly even better, improve [`d3-array`](https://github.com/d3/d3-array), `d3-collection`, and `d3-shape` to make sure this is supported.
 
Looking at [d3-array](https://github.com/d3/d3-array) it does have a `module` field, which links to the original/untouched/raw source code. I don't know enough yet to understand why this doesn't work.

**Comment by micahstubbs** [comment]
@peteruithoven thanks for the additional detail.  I'm sure that @tomshanley and I would be happy to review a PR, if you want to have a go at implementing some of these improved packaging ideas for **d3-sankey-circular**

As you note in https://github.com/tomshanley/d3-sankey-circular/issues/32#issuecomment-466967873, the best solution probably involves convincing the authors of the other d3 modules that **d3-sankey-circular** depends on to improve their packaging.  If you can convince them to do that, I'll be impressed 😄 

[citation needed], but I remember reading somewhere the sentiment that, this whole `javascript modules` space has not "settled down" yet.  Standards and implementations are still changing, and smart people still disagree about such things.  In this alpha environment, library authors prefer to pick their favorite implementation of `javascript modules` and push the complexity of consuming those modules downstream to the users and their custom webpack config. I'm not saying that this is ideal, just that this is the state of the landscape right now 🤷‍♂️

**Comment by micahstubbs** [comment]
@peteruithoven I'd be curious to see if other bundlers like [parcel](https://github.com/parcel-bundler/parcel) that advertise themselves as _zero-config_ would be able to parse the `.mjs` from **d3-cirucular-sankey** as is 🤔

**Comment by brylie** [comment]
> I remember reading somewhere the sentiment that, this whole javascript modules space has not "settled down" yet.

ES Modules syntax was standardized in ES6. It is now the default import/export style in Angular, Aurelia, Ember, React, lodash, Meteor, moment, Vue, and many other projects. While not yet universally adopted, now is a good time for projects to adopt ES module syntax.

**Comment by tomshanley** [comment]
Thanks @brylie - just so I'm clear, do you recommend that I don't incorporate the change proposed in #33 ?

**Comment by brylie** [comment]
Ah, #33 looks fine.

**Comment by tomshanley** [comment]
thanks @brylie - I appreciate your expertise on this
